modLoader = "javafml"
loaderVersion = "${neoforge_loader}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
iconFile = "assets/${id}/icon.png"
logoFile = "assets/${id}/banner.png"
bannerFile = "assets/${id}/banner.png"
logoBlur = false
displayName = "${name}"
displayURL = "${homepage}"
authors = "${authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${description}'''
issueTrackerURL = "${issues}"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "hbhap.mixins.json"

[modproperties.${id}]
catalogueImageIcon = "assets/${id}/icon.png"
catalogueBackground = "assets/${id}/background.png"
